// ===== Main =====
SET vLib = 'lib://BUT3/Projet';

// ===== Provinces =====
Provinces:
LOAD
    code as CodeProvince,
    libelle as Province,
    type as TypeProvince,
    capitale as Capitale
FROM [$(vLib)/provinces.csv]
(txt, utf8, embedded labels, delimiter is ';', msq);

// ===== EPA =====
EPA:
LOAD
    @1 as Annee,
    @2 as Province,
    @4 as Indicateur,
    @5 as Profession,
    @6 as Genre,
    @13 as Valeur,
    @14 as Statut
FROM [$(vLib)/population.csv]
(txt, utf8, no labels, delimiter is ',', msq);

// ===== EIMT (un seul fichier pour commencer) =====
EIMT:
LOAD
    A as ProvinceBrute,
    B as Volet,
    C as Employeur,
    D as Adresse,
    E as ProfessionBrute,
    G as EIMTApprouvees,
    H as PostesApprouves
FROM [$(vLib)/tfwp_2026q1_pos_fr.xlsx]
(ooxml, no labels, header is 2 lines, table is Sheet1);
